[package]
name = "bevy-craft"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14"
bevy_framepace = "0.17"
iyes_perf_ui = "0.3"
arrayvec = "0.7"
rand = "0.8"
rand_chacha = "0.3"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[toolchain]
channel = "nightly"
