[package]
name = "bevy-craft"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14"
avian2d = "0.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[toolchain]
channel = "nightly"
